_target_: src.datamodules.ICASSPDatamodule

name: icassp_task3
batch_size: 8
num_workers: 6

data_path: ${oc.env:ICASSP_TASK3_PATH}
orig_data_path: ${oc.env:ICASSP_ORIG_PATH}
task_idx: 3

idx_to_freq:
  f1: 0.868
  f2: 1.8
  f3: 3.5
max_freq: 10
mixup_ratio: 0.75
rotate_ratio: 0.0
crop_ratio: 0.75
crop_size: null
channels_to_use: null